[package]
name = "touying-simpl-bupt"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Yokumi"]
license = "MIT"
description = "北京邮电大学 Touying 幻灯片主题 (Touying Slide Theme for BUPT)"
repository = "https://github.com/Yokumii/BUPT-Slide-Template-by-Typst.git"
keywords = ["touying", "slide", "bupt", "北京邮电大学"]
categories = ["presentation"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
